# Generated by Django 4.2 on 2023-04-10 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
